---
# This key selects the language support used for the build.
language: python

# Travis CI environments do not start services by default, 
# to make more RAM available to build scripts.
services:
  - docker

# Global env add vars for all env, jobs or matrix execute a new build with this vars
env:
  global:
    - ANSILE_ROLE_NAME: kibana
  jobs:
    - MOLECULE_ENV_TEST: centos7

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule docker
# - pip install required driver (e.g. docker, python-vagrant, shade, boto etc.)

script:
  - molecule test